[book]
language = "en"
multilingual = false
src = "src"
title = "Rust for Java Developers"

[output.html]
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/chrischiedo/rust-for-java-devs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/chrischiedo/rust-for-java-devs/edit/main/{path}"

[output.html.playground]
runnable = false
